Models/Domain/Combustivel.cs
using System;
using System.Collections.Generic;
using System.Text;
using UaiFuel.Models.DAO;

namespace UaiFuel.Models.Domain
{

    /** 
     * POCO Design Pattern
     */
    public class Combustivel : IDomainObject
    {

        // Properties   -------------------------------------------------------------------------------------

        public int Id { get; set; }
        public Posto Posto { get; set; }
        public string Nome { get; set; }        
        public StatusCombustivel Status { get; set; }


        // Constructors  -------------------------------------------------------------------------------------

        public Combustivel() { }


        // Override's Methods     ---------------------------------------------------------------------------

        public override string ToString()
        {
            return $"{Id} - {Nome}";
        }

        public override bool Equals(object obj)
        {
            return obj is Combustivel combustivel &&
                    Posto == combustivel.Posto &&
                    Id == combustivel.Id;
        }

        public override int GetHashCode()
        {
            return HashCode.Combine(Id);
        }
    }
}

Models/ViewModel/CombustivelViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using UaiFuel.Models.Domain;

namespace UaiFuel.Models.ViewModel
{
    public class CombustivelViewModel
    {
        public int Id { get; set; }

        [Display(Name = "Nome")]
        [Required(ErrorMessage = "Campo Nome é obrigatório.")]
        public string Nome { get; set; }

        [Display(Name = "Status")]
        [Required(ErrorMessage = "Campo Status é obrigatório.")]
        public string CodigoStatus { get; set; }

        public List<SelectListItem> Statuses { get; private set; }
        public List<SelectListItem> Postos { get; set; }

        public CombustivelViewModel() 
        {
            CodigoStatus = StatusCombustivel.EM_ESTOQUE.Codigo.ToString();
            Statuses = new List<SelectListItem>();
            foreach (var status in StatusCombustivel.lista)
            {
                Statuses.Add(
                    new SelectListItem
                    {
                        Value = status.Codigo.ToString(),
                        Text = status.Descricao
                    });
            }
        }


        public CombustivelViewModel(Combustivel combustivel) :
            this()
        {
            Id = combustivel.Id;
            Nome = combustivel.Nome;
            CodigoStatus = combustivel.Status.Codigo.ToString();                        
        }
    }
}

Controllers/CombustivelController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using UaiFuel.Models.DAO;
using UaiFuel.Models.Domain;
using UaiFuel.Models.Service;
using UaiFuel.Models.Utils;
using UaiFuel.Models.ViewModel;

namespace UaiFuel.Controllers
{
    public class CombustivelController : Controller       
    {
        private readonly CombustivelService service;
        private readonly PostoService postoService;

        public CombustivelController()
        {
            service = new CombustivelService();
            postoService = new PostoService();
        }


        public IActionResult List()
        {   
            return View(service.Read());
        }


        public IActionResult Delete(int id)
        {
            service.Delete(id);
            return RedirectToAction("List");
        }


        public IActionResult Create()
        {
            CreateCombustivelViewModel vm = new CreateCombustivelViewModel();
            CarregarPostos(vm);
            return View(vm);
        }

        
        [HttpPost]
        public IActionResult Create(CreateCombustivelViewModel vm)
        {

            if (!ModelState.IsValid)
            {
                IEnumerable<ModelError> allErrors = ModelState.Values.SelectMany(v => v.Errors);
                IEnumerable<string> messages = allErrors.Select(x => x.ErrorMessage);

                FrontUtil.SetupErrorsViewBag(this, messages);

                foreach (var modelValue in ModelState.Values)
                {
                    modelValue.Errors.Clear();
                }
                CarregarPostos(vm);

                return View(vm);
            }
            
            Combustivel combustivel = new Combustivel
            {
                Posto = new Posto { Id = Convert.ToInt32(vm.PostoId)},
                Nome = vm.Nome,
                Status = StatusCombustivel.getInstance(Convert.ToInt32(vm.CodigoStatus))
            };
            service.Create(combustivel);

            return RedirectToAction("List");
        }


        [HttpGet]
        public IActionResult Update(int id)
        {
            Combustivel combustivel = service.Read(id);  
            var vm = new UpdateCombustivelViewModel(combustivel);

            return View(vm);
        }
        

        [HttpPost]
        public IActionResult Update(int id, UpdateCombustivelViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                IEnumerable<ModelError> allErrors = ModelState.Values.SelectMany(v => v.Errors);
                IEnumerable<string> messages = allErrors.Select(x => x.ErrorMessage);

                FrontUtil.SetupErrorsViewBag(this, messages);

                foreach (var modelValue in ModelState.Values)
                {
                    modelValue.Errors.Clear();
                }

                return View(vm);
            }

            Combustivel combustivel = new Combustivel
            {
                Id = id,
                Nome = vm.Nome,
                Status = StatusCombustivel.getInstance(Convert.ToInt32(vm.CodigoStatus))
            };
            service.Update(combustivel);
            
            return RedirectToAction("List");
        }


        private void CarregarPostos(CreateCombustivelViewModel vm)
        {
            IList<Posto> postos = postoService.Read();
            foreach (Posto posto in postos)
            {
                vm.Postos.Add(
                    new SelectListItem
                    {
                        Value = posto.Id.ToString(),
                        Text = posto.Nome
                    });
            }
        }
    }
}

Views/Combustivel/Create.cshtml
@model CreateCombustivelViewModel

<form asp-controller="Combustivel" asp-action="Create" method="POST">
    <div class="container">
        <div class="wrapper">
            <h2 style="margin-bottom:2rem;">Novo Combustível</h2>
            @if (ViewBag.ErrorMessages != null)
            {
                @Html.Raw(ViewBag.ErrorMessages);
            }
            else if (ViewBag.Message != null)
            {
                <div class="@ViewBag.CssClass">
                    @ViewBag.Message
                </div>
            }
            <div class="content">
                <div class="tab_wrap" style="display: block;">
                    <div class="form-group mb-3 row">
                        <label class="col-md-3 col-form-label">
                            Posto
                            <span class="required">*</span>
                        </label>
                        <div class="col-sm-6">
                            <select asp-for="PostoId" class="custom-select form-select-lg mb-3">
                                <option value="">Selecione</option>
                                @foreach (var posto in @Model.Postos)
                                {
                                    <option value="@posto.Value">@posto.Text</option>
                                }
                            </select>
                            <span asp-validation-for="PostoId"></span>
                        </div>
                    </div>
                    <div class="form-group mb-3 row">
                        <label class="col-md-3 col-form-label" asp-for="Nome">
                            Nome
                            <span class="required">*</span>
                        </label>
                        <div class="col-sm-6">
                            <input asp-for="Nome" class="form-control input-sm mb-3" />
                            <span asp-validation-for="Nome"></span>
                        </div>
                    </div>
                    <div class="form-group mb-3 row">
                        <label class="col-md-3 col-form-label">
                            Status
                            <span class="required">*</span>
                        </label>
                        <div class="col-sm-6">
                            <select asp-for="CodigoStatus" class="custom-select form-select-lg mb-3">
                                <option value="">Selecione</option>
                                @foreach (var status in @Model.Statuses)
                                {
                                    <option value="@status.Value">@status.Text</option>
                                }
                            </select>
                            <span asp-validation-for="CodigoStatus"></span>
                        </div>
                    </div>
                </div>
            </div>
            <button style="margin-top:2rem;" class="btn btn-primary">Salvar</button>
        </div>
    </div>
</form>

Views/Combustivel/List.cshtml
@model IList<Combustivel>

<div class="list_container">
    <h2 style="margin-bottom:2rem;">Combustíveis Cadastrados</h2>
    @if (ViewBag.ErrorMessages != null)
    {
        @Html.Raw(ViewBag.ErrorMessages);
    }
    else if (ViewBag.Message != null)
    {
        <div class="@ViewBag.CssClass">
            @ViewBag.Message
        </div>
    }
    <table class="table table-bordered table-hover table-sm" id="sortTable">
        <thead>
            <tr>
                <th>Posto</th>
                <th>Nome</th>
                <th>Status</th>
                <th>Ação</th>
            </tr>
        </thead>

        @foreach (Combustivel c in Model)
        {
            <tr>
                <td>@c.Posto.Nome</td>
                <td>@c.Nome</td>
                <td>@c.Status</td>
                <td>
                    <a class="btn btn-sm btn-danger"
                       href="/combustivel/delete/@c.Id" title="Apagar"><i class="fas fa-trash-alt"></i></a>
                    <a class="btn btn-sm btn-warning"
                       href="/combustivel/update/@c.Id" title="Editar"><i class="fas fa-edit"></i></a>
                </td>
            </tr>
        }

        <tfoot>
            <tr>
                <td>Posto</td>
                <td>Nome</td>
                <td>Status</td>
                <td>Ação</>
            </tr>
        </tfoot>
    </table>
</div>

<a class="btn btn-primary" href="/combustivel/create"><i class="fas fa-plus"></i>   Novo Combustível</a>

<script>$('#sortTable').DataTable({
    "paging":   true,
    "ordering": true,
    "info":     false,
    "language":{
        "lengthMenu":     "Exibir _MENU_ registros",
        "zeroRecords": "Nenhum registro encontrado",
        "info": "Quantidade de páginas _PAGE_ a _PAGES_",
        "infoEmpty": "Nenhum registro encontrado",
        "infoFiltered": "",
        "search":"Filtro:","paginate": {
                                "first":      "Primeiro",
                                "last":       "Último",
                                "next":       "Próximo",
                                "previous":   "Anterior"
        },
    }
});</script>

Views/Combustivel/Update.cshtml
@model UpdateCombustivelViewModel

<form asp-controller="Combustivel" asp-action="Update" method="POST">
    <div class="container">
        <div class="wrapper">
            <h2 style="margin-bottom:2rem;">Edição de Combustível</h2>
            @if (ViewBag.ErrorMessages != null)
            {
                @Html.Raw(ViewBag.ErrorMessages);
            }
            else if (ViewBag.Message != null)
            {
                <div class="@ViewBag.CssClass">
                    @ViewBag.Message
                </div>
            }
            <div class="content">
                <div class="tab_wrap" style="display: block;">
                    <div class="form-group mb-3 row">
                        <label class="col-md-3 col-form-label" asp-for="Posto">
                            Posto
                        </label>
                        <div class="col-sm-6">
                            <input readonly="readonly" asp-for="Posto" class="form-control input-sm mb-3" />
                            <span asp-validation-for="Posto"></span>
                        </div>
                    </div>
                    <div class="form-group mb-3 row">
                        <label class="col-md-3 col-form-label" asp-for="Nome">
                            Nome
                            <span class="required">*</span>
                        </label>
                        <div class="col-sm-6">
                            <input asp-for="Nome" class="form-control input-sm mb-3" />
                            <span asp-validation-for="Nome"></span>
                        </div>
                    </div>
                    <div class="form-group mb-3 row">
                        <label class="col-md-3 col-form-label">
                            Status
                            <span class="required">*</span>
                        </label>
                        <div class="col-sm-6">
                            <select asp-for="CodigoStatus" class="custom-select form-select-lg mb-3">
                                <option value="">Selecione</option>
                                @foreach (var status in @Model.Statuses)
                                {
                                    <option value="@status.Value">@status.Text</option>
                                }
                            </select>
                            <span asp-validation-for="CodigoStatus"></span>
                        </div>
                    </div>
                </div>
            </div>
            <button style="margin-top:2rem;" class="btn btn-primary">Guardar</button>
        </div>
    </div>
</form>