Models/Domain/Veiculo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text;
using UaiFuel.Models.DAO;

namespace UaiFuel.Models.Domain
{
    /** 
     * POCO Design Pattern
     */
    public class Veiculo : IDomainObject
    {
        
        // Properties   -------------------------------------------------------------------------------------

        public string Placa { get; set; }   // PK
        public string Cor { get; set; }
        public string Modelo { get; set; }
        public int AnoFabricacao { get; set; }
        public int AnoModelo { get; set; }
        public StatusVeiculo Status { get; set; }


        // Constructors     ---------------------------------------------------------------------------------

        public Veiculo() 
        {
            Status = StatusVeiculo.ATIVO;
        }


        // Object Overrides Methods     ---------------------------------------------------------------------   

        public override string ToString()
        {
            return $"Veículo: placa {Placa}";
        }

        public override bool Equals(object obj)
        {
            return obj is Veiculo veiculo &&
                   Placa == veiculo.Placa;
        }

        public override int GetHashCode()
        {
            return HashCode.Combine(Placa);
        }
    }
}

Models/ViewModel/VeiculoViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using UaiFuel.Models.Domain;

namespace UaiFuel.Models.ViewModel
{
    public class VeiculoViewModel
    {
        [Display(Name = "Placa")]
        [Required(ErrorMessage = "Placa do Veículo é campo obrigatório.")]
        public string Placa { get; set; }   // PK


        [Display(Name = "Cor")]
        [Required(ErrorMessage = "Cor é campo obrigatório.")]
        public string Cor { get; set; }


        [Display(Name = "Modelo")]
        [Required(ErrorMessage = "Modelo é campo obrigatório.")]
        public string Modelo { get; set; }


        [Display(Name = "Ano Fabricação")]
        [Required(ErrorMessage = "Ano de Fabricação é campo obrigatório.")]
        public string AnoFabricacao { get; set; }


        [Display(Name = "Ano Modelo")]
        [Required(ErrorMessage = "Ano Modelo é campo obrigatório.")]
        public string AnoModelo { get; set; }


        [Display(Name = "Status")]
        [Required(ErrorMessage = "Status é campo obrigatório.")]
        public string CodigoStatus { get; set; }

        public List<SelectListItem> Statuses { get; set; }
        
        public VeiculoViewModel() 
        {
            Statuses = new List<SelectListItem>();
            foreach (var status in StatusVeiculo.lista)
            {
                Statuses.Add(
                    new SelectListItem
                    {
                        Value = status.Codigo.ToString(),
                        Text = status.Descricao
                    });
            }            
        }


        public VeiculoViewModel(Veiculo veiculo) :
            this()
        {
            Placa = veiculo.Placa;
            Cor = veiculo.Cor;
            Modelo = veiculo.Modelo;
            AnoFabricacao = veiculo.AnoFabricacao.ToString();
            AnoModelo = veiculo.AnoModelo.ToString();
            CodigoStatus = veiculo.Status.Codigo.ToString();
        }

    }

}

Controllers/VeiculoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using UaiFuel.Models.DAO;
using UaiFuel.Models.Domain;
using UaiFuel.Models.ExceptionCore;
using UaiFuel.Models.Service;
using UaiFuel.Models.Utils;
using UaiFuel.Models.ViewModel;

namespace UaiFuel.Controllers
{
    [Route("veiculo")]
    public class VeiculoController : Controller       
    {
        private readonly VeiculoService service;

        public VeiculoController()
        {
            service = new VeiculoService();
        }

        [Route("list")]
        public IActionResult List()
        {   
            return View(service.Read());
        }


        [Route("delete/{placa}")]
        public IActionResult Delete(string placa)
        {
            service.Delete(placa);
            return RedirectToAction("List");
        }

        [Route("create")]
        public IActionResult Create()
        {
            return View(new VeiculoViewModel());
        }


        [HttpPost]
        [Route("create")]
        public IActionResult Create(VeiculoViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                IEnumerable<ModelError> allErrors = ModelState.Values.SelectMany(v => v.Errors);
                IEnumerable<string> messages = allErrors.Select(x => x.ErrorMessage);

                FrontUtil.SetupErrorsViewBag(this, messages);

                foreach (var modelValue in ModelState.Values)
                {
                    modelValue.Errors.Clear();
                }

                return View(vm);
            }
            Veiculo veiculo = new Veiculo
            { 
                Placa = vm.Placa,
                Cor = vm.Cor,
                Modelo = vm.Modelo,
                AnoFabricacao = Convert.ToInt32(vm.AnoFabricacao),
                AnoModelo = Convert.ToInt32(vm.AnoModelo),
                Status = StatusVeiculo.getInstance(Convert.ToInt32(vm.CodigoStatus))
            };
            try
            {
                service.Create(veiculo);
                return RedirectToAction("List");
            }
            catch (AppException exp)
            {
                FrontUtil.SetupViewBag(this, exp);
                return View(vm);
            }
        }


        [HttpGet]
        [Route("update/{placa}")]
        public IActionResult Update(string placa)
        {
            Veiculo veiculo = service.Read(placa);
            var vm = new VeiculoViewModel(veiculo);

            return View(vm);
        }
        
        [HttpPost]
        [Route("update/{placa}")]
        public IActionResult Update(string placa, VeiculoViewModel vm)
        {

            if (!ModelState.IsValid)
            {
                IEnumerable<ModelError> allErrors = ModelState.Values.SelectMany(v => v.Errors);
                IEnumerable<string> messages = allErrors.Select(x => x.ErrorMessage);

                FrontUtil.SetupErrorsViewBag(this, messages);

                foreach (var modelValue in ModelState.Values)
                {
                    modelValue.Errors.Clear();
                }

                return View(vm);
            }

            Veiculo veiculo = new Veiculo
            {
                Placa = vm.Placa,
                Cor = vm.Cor,
                Modelo = vm.Modelo,
                AnoFabricacao = Convert.ToInt32(vm.AnoFabricacao),
                AnoModelo = Convert.ToInt32(vm.AnoModelo),
                Status = StatusVeiculo.getInstance(Convert.ToInt32(vm.CodigoStatus))
            };
            try
            {
                service.Update(veiculo);
                return RedirectToAction("List");
            }
            catch (AppException exp)
            {
                FrontUtil.SetupViewBag(this, exp);
                return View(vm);
            }            
        }
    }
}

Views/Veiculo/Create.cshtml
@model VeiculoViewModel

<form asp-controller="Veiculo" asp-action="Create" method="POST">
    <div class="container">
        <div class="wrapper">
            <h2 style="margin-bottom:2rem;">Novo Veículo</h2>
            @if (ViewBag.ErrorMessages != null)
            {
                @Html.Raw(ViewBag.ErrorMessages);
            }
            else if (ViewBag.Message != null)
            {
                <div class="@ViewBag.CssClass">
                    @ViewBag.Message
                </div>
            }
            <div class="content">
                <div class="tab_wrap" style="display: block;">
                    <div class="form-group mb-3 row">
                        <label class="col-md-3 col-form-label" asp-for="Placa">
                            Placa
                            <span class="required">*</span>
                        </label>
                        <div class="col-sm-6">
                            <input asp-for="Placa" class="form-control" />
                            <span asp-validation-for="Placa"></span>
                        </div>
                    </div>

                    <div class="form-group mb-3 row">
                        <label class="col-md-3 col-form-label" asp-for="Cor">
                            Cor
                            <span class="required">*</span>
                        </label>
                        <div class="col-sm-6">
                            <input asp-for="Cor" class="form-control" />
                            <span asp-validation-for="Cor"></span>
                        </div>
                    </div>

                    <div class="form-group mb-3 row">
                        <label class="col-md-3 col-form-label">
                            Status
                            <span class="required">*</span>
                        </label>
                        <div class="col-sm-6">
                            <select asp-for="CodigoStatus" class="form-control">
                                <option value="">Selecione</option>
                                @foreach (var status in @Model.Statuses)
                                {
                                    <option value="@status.Value">@status.Text</option>
                                }
                            </select>
                            <span asp-validation-for="CodigoStatus"></span>
                        </div>
                    </div>

                    <div class="form-group mb-3 row">
                        <label class="col-md-3 col-form-label" asp-for="Modelo">
                            Modelo
                            <span class="required">*</span>
                        </label>
                        <div class="col-sm-6">
                            <input asp-for="Modelo" class="form-control" />
                            <span asp-validation-for="Modelo"></span>
                        </div>
                    </div>

                    <div class="form-group mb-3 row">
                        <label class="col-md-3 col-form-label" asp-for="AnoModelo">
                            Ano do Modelo
                            <span class="required">*</span>
                        </label>
                        <div class="col-sm-6">
                            <input asp-for="AnoModelo" class="form-control" />
                            <span asp-validation-for="AnoModelo"></span>
                        </div>
                    </div>

                    <div class="form-group mb-3 row">
                        <label class="col-md-3 col-form-label" asp-for="AnoFabricacao">
                            Ano de Fabricação
                            <span class="required">*</span>
                        </label>
                        <div class="col-sm-6">
                            <input asp-for="AnoFabricacao" class="form-control" />
                            <span asp-validation-for="AnoFabricacao"></span>
                        </div>
                    </div>
                </div>
            </div>
            <button style="margin-top:2rem;" class="btn btn-primary">Salvar</button>
        </div>
    </div>
</form>

Views/Veiculo/List.cshtml
@model IList<Veiculo>

<div class="list_container">
    <h2 style="margin-bottom:2rem;">Veículos Cadastrados</h2>
    @if (ViewBag.ErrorMessages != null)
    {
        @Html.Raw(ViewBag.ErrorMessages);
    }
    else if (ViewBag.Message != null)
    {
        <div class="@ViewBag.CssClass">
            @ViewBag.Message
        </div>
    }
    <table class="table table-bordered table-hover table-sm" id="sortTable">
        <thead>
            <tr>
                <th>Placa</th>
                <th>Cor</th>
                <th>Status</th>
                <th>Modelo</th>
                <th>Ano Fabricação</th>
                <th>Ano Modelo</th>
                <th>Ação</th>
            </tr>
        </thead>
        @foreach (Veiculo v in Model)
        {
            <tr>
                <td>@v.Placa</td>
                <td>@v.Cor</td>
                <td>@v.Status</td>
                <td>@v.Modelo</td>
                <td>@v.AnoFabricacao</td>
                <td>@v.AnoModelo</td>
                <td>
                    <a class="btn btn-sm btn-danger"
                       href="/veiculo/delete/@v.Placa" title="Apagar"><i class="fas fa-trash-alt"></i></a>
                    <a class="btn btn-sm btn-warning"
                       href="/veiculo/update/@v.Placa" title="Editar"><i class="fas fa-edit"></i></a>
                </td>
            </tr>
        }

        <tfoot>
            <tr>
                <td>Placa</td>
                <td>Cor</td>
                <td>Status</td>
                <td>Modelo</td>
                <td>AnoFabricacao</td>
                <td>AnoModelo</td>
                <td>Ação</>
            </tr>
        </tfoot>
    </table>
</div>
    <a class="btn btn-primary" href="/veiculo/create"><i class="fas fa-plus"></i>   Novo Veículo</a>
    <script>
$('#sortTable').DataTable({
    "paging":   true,
    "ordering": true,
    "info":     false,
    "language":{
        "lengthMenu":     "Exibir _MENU_ registros",
        "zeroRecords": "Nenhum registro encontrado",
        "info": "Quantidade de páginas _PAGE_ a _PAGES_",
        "infoEmpty": "Nenhum registro encontrado",
        "infoFiltered": "",
        "search":"Filtro:","paginate": {
                                "first":      "Primeiro",
                                "last":       "Último",
                                "next":       "Próximo",
                                "previous":   "Anterior"
        },
    }
});</script>

Views/Veiculo/Update.cshtml
@model VeiculoViewModel

<form asp-controller="Veiculo" asp-action="Update" method="POST">
    <div class="container">
        <div class="wrapper">
            <h2 style="margin-bottom:2rem;">Edição de Veículo</h2>
            @if (ViewBag.ErrorMessages != null)
            {
                @Html.Raw(ViewBag.ErrorMessages);
            }
            else if (ViewBag.Message != null)
            {
                <div class="@ViewBag.CssClass">
                    @ViewBag.Message
                </div>
            }
            <div class="content">
                <div class="tab_wrap" style="display: block;">
                    <div class="form-group mb-3 row">
                        <label class="col-md-3 col-form-label" asp-for="Placa">
                            Placa
                            <span class="required">*</span>
                        </label>
                        <div class="col-sm-6">
                            <input readonly="readonly" asp-for="Placa" class="form-control" />
                            <span asp-validation-for="Placa"></span>
                        </div>
                    </div>

                    <div class="form-group mb-3 row">
                        <label class="col-md-3 col-form-label" asp-for="Cor">
                            Cor
                            <span class="required">*</span>
                        </label>
                        <div class="col-sm-6">
                            <input asp-for="Cor" class="form-control" />
                            <span asp-validation-for="Cor"></span>
                        </div>
                    </div>

                    <div class="form-group mb-3 row">
                        <label class="col-md-3 col-form-label">
                            Status
                            <span class="required">*</span>
                        </label>
                        <div class="col-sm-6">
                            <select asp-for="CodigoStatus" class="form-control">
                                <option value="">Selecione</option>
                                @foreach (var status in @Model.Statuses)
                                {
                                    <option value="@status.Value">@status.Text</option>
                                }
                            </select>
                            <span asp-validation-for="CodigoStatus"></span>
                        </div>
                    </div>

                    <div class="form-group mb-3 row">
                        <label class="col-md-3 col-form-label" asp-for="Modelo">
                            Modelo
                            <span class="required">*</span>
                        </label>
                        <div class="col-sm-6">
                            <input asp-for="Modelo" class="form-control" />
                            <span asp-validation-for="Modelo"></span>
                        </div>
                    </div>

                    <div class="form-group mb-3 row">
                        <label class="col-md-3 col-form-label" asp-for="AnoFabricacao">
                            AnoFabricacao
                            <span class="required">*</span>
                        </label>
                        <div class="col-sm-6">
                            <input asp-for="AnoFabricacao" class="form-control" />
                            <span asp-validation-for="AnoFabricacao"></span>
                        </div>
                    </div>

                    <div class="form-group mb-3 row">
                        <label class="col-md-3 col-form-label" asp-for="AnoModelo">
                            AnoModelo
                            <span class="required">*</span>
                        </label>
                        <div class="col-sm-6">
                            <input asp-for="AnoModelo" class="form-control" />
                            <span asp-validation-for="AnoModelo"></span>
                        </div>
                    </div>
                </div>
            </div>
            <button style="margin-top:2rem;" class="btn btn-primary">Guardar</button>
        </div>
    </div>
</form>