Models/Domain/Abastecimento.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text;
using UaiFuel.Models.DAO;


namespace UaiFuel.Models.Domain
{
 
    public class Abastecimento : IDomainObject
    {
        // Properties   -------------------------------------------------------------------------------------

        public int Id { get; set; }
        public DateTime DataCriacao { get; set; }
        public string CupomFiscal { get; set; }
        public decimal ValorTotal { get; set; }
        public StatusAbastecimento Status { get; set; }
        public IList<AbastecimentoCombustivel> Combustiveis { get; set; }
        // Composições
        public Posto Posto { get; set; }
        public Motorista Motorista { get; set; }
        public Veiculo Veiculo { get; set; }


        // Constructors     ---------------------------------------------------------------------------------

        public Abastecimento()
        {
            DataCriacao = DateTime.Now;
            Status = StatusAbastecimento.PENDENTE_PAGTO;
            Combustiveis = new List<AbastecimentoCombustivel>();
        }


        // Methods      -------------------------------------------------------------------------------------

        
        public void RemoverCombustivel(Combustivel combustivel)
        {
            IEnumerator<AbastecimentoCombustivel> enumerator = Combustiveis.GetEnumerator();
            while( enumerator.MoveNext() )
            {
                AbastecimentoCombustivel ac = enumerator.Current;

                if ( ac.Abastecimento.Equals(this) && ac.Combustivel.Equals(combustivel) )
                {
                    // Remove da coleção de combustíveis
                    enumerator.Dispose();
                    // Garbage Collector - recolher memória
                    ac.Abastecimento = null;
                    ac.Combustivel = null;
                }
            }
        }


        public override string ToString()
        {
            return $"abast_id: {Id}";
        }


        public override bool Equals(object obj)
        {
            return obj is Abastecimento abastecimento &&
                   Id == abastecimento.Id;
        }


        public override int GetHashCode()
        {
            return HashCode.Combine(Id);
        }
    }
}

Models/ViewModel/AbastecimentoViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using UaiFuel.Models.Domain;

namespace UaiFuel.Models.ViewModel
{
    public class AbastecimentoViewModel
    {

        public int Id { get; set; }
        public string CupomFiscal { get; set; }
        
        [DataType(DataType.Currency)]
        public string ValorTotal { get; set; }


        [Display(Name = "Status")]
        [Required(ErrorMessage = "Status é campo obrigatório.")]
        public string CodigoStatus { get; set; }
        public List<SelectListItem> Statuses { get; private set; }


        [Display(Name = "Posto")]
        [Required(ErrorMessage = "Selecione em qual Posto está ocorrendo o abastecimento.")]
        public string PostoIdHidden { get; set; }
        public string PostoId { get; set; }
        public string NomePosto { get; set; }
        public List<SelectListItem> Postos { get; set; }


        [Display(Name = "Motorista")]
        [Required(ErrorMessage = "Selecione qual Motorista está realizando o abastecimento.")]
        public string MotoristaId { get; set; }
        public List<SelectListItem> Motoristas { get; set; }


        [Display(Name = "Veículo")]
        [Required(ErrorMessage = "Selecione o Veículo que está sendo abastecido.")]
        public string VeiculoPlaca { get; set; }
        public List<SelectListItem> Veiculos { get; set; }


        public int CombustivelId { get; set; }
        public List<SelectListItem> Combustiveis { get; set; }


        public string NomeCombustivel { get; set; }
        public string Litros { get; set; }
        public string Valor { get; set; }
        public bool IsBotaoAdicionarCombustivel { get; set; }

        public List<ItemViewModel> Items { get; set; }

        public AbastecimentoViewModel() 
        {
            IsBotaoAdicionarCombustivel = false;
            Postos = new List<SelectListItem>();
            Motoristas = new List<SelectListItem>();
            Veiculos = new List<SelectListItem>();
            Combustiveis = new List<SelectListItem>();

            CodigoStatus = StatusAbastecimento.PENDENTE_PAGTO.Codigo.ToString();
            Statuses = new List<SelectListItem>();
            foreach (var status in StatusAbastecimento.lista)
            {
                Statuses.Add(
                    new SelectListItem
                    {
                        Value = status.Codigo.ToString(),
                        Text = status.Descricao
                    });
            }
        }



    }
}

Controllers/AbastecimentoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using UaiFuel.Models.DAO;
using UaiFuel.Models.Domain;
using UaiFuel.Models.Service;
using UaiFuel.Models.Utils;
using UaiFuel.Models.ViewModel;

namespace UaiFuel.Controllers
{
    public class AbastecimentoController : Controller       
    {
        private readonly AbastecimentoService service;
        private readonly CombustivelService combustivelService;
        private readonly PostoService postoService;
        private readonly MotoristaService motoristaService;
        private readonly VeiculoService veiculoService;

        public AbastecimentoController()
        {
            service = new AbastecimentoService();
            combustivelService = new CombustivelService();
            postoService = new PostoService();
            motoristaService = new MotoristaService();
            veiculoService = new VeiculoService();
        }

            public IActionResult List()
        {   
            return View(service.Read());
        }


        public IActionResult Delete(int id)
        {
            service.Delete(id);
            return RedirectToAction("List");
        }


        public IActionResult Pesquisar()
        {
            PesquisaAbastecimentoViewModel vm = new PesquisaAbastecimentoViewModel();
            CarregarListaCombosPesquisa(vm);
            return View(vm);
        }

        
        [HttpPost]
        public IActionResult Pesquisar(PesquisaAbastecimentoViewModel vm)
        {
            vm.DataInicial = Convert.ToDateTime(vm.StrDataInicial);
            vm.DataFinal   = Convert.ToDateTime(vm.StrDataFinal);
            if (vm.DataFinal != default(DateTime))
            {
                vm.DataFinal = vm.DataFinal.AddDays(1);
            }
            vm.Abastecimentos = service.Pesquisar(vm);
            vm.RealizouPesquisa = true;
            CarregarListaCombosPesquisa(vm);
            return View(vm);
        }


        public IActionResult Create()
        {
            // Caso tenha itens_combustível e valor total na sessão de outro abastecimento,
            // vamos limpar tudo
            FrontUtil.ExtractFromSession<List<ItemViewModel>>(this.HttpContext, "itens");
            FrontUtil.ExtractFromSession<decimal>(this.HttpContext, "total"); 
            AbastecimentoViewModel vm = new AbastecimentoViewModel();
            CarregarListaCombos(vm);
            return View(vm);
        }

        
        [HttpPost]
        public JsonResult GetCombustiveis(int postoId)
        {
            List<List<string>> combustiveisJson = new List<List<string>>();


            IList<Combustivel> combustiveis = combustivelService.ReadByPosto(postoId);
            foreach (Combustivel combustivel in combustiveis)
            {
                List<string> dict = new List<string>
                {
                    combustivel.Id.ToString(),
                    combustivel.Nome
                };
                combustiveisJson.Add(dict);
                }

            return new JsonResult(combustiveisJson);
        }


        [HttpPost]
        public IActionResult Create(AbastecimentoViewModel vm)
        {
            if (vm.IsBotaoAdicionarCombustivel)
            {
                // Limpar erros de validações - não vou criar abastecimento ainda
                IEnumerable<ModelError> allErrors = ModelState.Values.SelectMany(v => v.Errors);
                IEnumerable<string> messages = allErrors.Select(x => x.ErrorMessage);

                foreach (var modelValue in ModelState.Values)
                {
                    modelValue.Errors.Clear();
                }

                // Cria item da linha da tabela
                ItemViewModel item = new ItemViewModel()
                {
                    CombustivelId = vm.CombustivelId,
                    NomeCombustivel = vm.NomeCombustivel,
                    PostoId = Convert.ToInt32(vm.PostoId),
                    NomePosto = vm.NomePosto,
                    Litros = vm.Litros,
                    Valor = vm.Valor
                };

                // Resgatar da sessão os item adicionados
                List<ItemViewModel> itens = FrontUtil.GetFromSession<List<ItemViewModel>>(
                        this.HttpContext, "itens");
                if (itens == null) itens = new List<ItemViewModel>();

                // Adiciona novo item combustível
                itens.Add(item);

                // Readiciona à sessão os a lista de combustível - itens 
                FrontUtil.AddToSession<List<ItemViewModel>>(this, "itens", itens);

                // Valor total do abastecimento
                decimal total, litros, valor;
                total = litros = valor = 0;
                foreach (var it in itens)
                {
                    litros = Convert.ToDecimal(it.Litros, new CultureInfo("pt-BR"));
                    valor = Convert.ToDecimal(it.Valor, new CultureInfo("pt-BR"));
                    total += valor * litros;
                }

                CarregarListaCombos(vm);
                //vm.Litros = null;
                //vm.Valor = null;
                //vm.ValorTotal = total.ToString();

                FrontUtil.AddToSession<decimal>(this, "total", total);
                ViewBag.FixarPosto = true;

                return View(vm);
            }

            else 
            {
                // Combustíveis
                List<ItemViewModel> itens = FrontUtil.ExtractFromSession<List<ItemViewModel>>(
                        this.HttpContext, "itens");
                
                // Valor total do abastecimento
                decimal valorTotal, litros, valor;
                valorTotal = litros = valor = 0;
                foreach (var it in itens)
                {
                    litros = Convert.ToDecimal(it.Litros, new CultureInfo("pt-BR"));
                    valor = Convert.ToDecimal(it.Valor, new CultureInfo("pt-BR"));
                    valorTotal += valor * litros;
                }
                
                // Abastecimento
                Abastecimento abastecimento = new Abastecimento()
                {
                    CupomFiscal = vm.CupomFiscal,
                    DataCriacao = DateTime.Now,
                    Motorista = new Motorista() { Id = Convert.ToInt32(vm.MotoristaId) },
                    Posto = new Posto() { Id = Convert.ToInt32(vm.PostoId) },
                    Veiculo = new Veiculo() { Placa = vm.VeiculoPlaca },
                    Status = StatusAbastecimento.getInstance(Convert.ToInt32(vm.CodigoStatus)), 
                    ValorTotal = valorTotal
                };

                // Adicionando Combustíveis ao Abastecimento
                foreach (var it in itens)
                {
                    litros = Convert.ToDecimal(it.Litros, new CultureInfo("pt-BR"));
                    valor = Convert.ToDecimal(it.Valor, new CultureInfo("pt-BR"));

                    Combustivel combustivel = new Combustivel() 
                    { 
                        Id = it.CombustivelId,
                        Posto = new Posto { Id = it.PostoId }
                    };
                    abastecimento.Combustiveis.Add(
                    new AbastecimentoCombustivel(abastecimento, combustivel)
                    {
                        Litros = litros,
                        Valor = valor
                    });
                }

                // Persistir Abastecimento
                service.Create(abastecimento);
            }
            return RedirectToAction("List");
        }



        [HttpGet]
        public IActionResult Update(int id)
        {
            Abastecimento abastecimento = service.Read(id);
            UpdateAbastecimentoViewModel vm = new UpdateAbastecimentoViewModel(abastecimento);

            return View(vm);
        }


        [HttpPost]
        public IActionResult Update(int id, UpdateAbastecimentoViewModel vm)
        {
            Abastecimento abastecimento = null;
            if (!ModelState.IsValid)
            {
                IEnumerable<ModelError> allErrors = ModelState.Values.SelectMany(v => v.Errors);
                IEnumerable<string> messages = allErrors.Select(x => x.ErrorMessage);

                FrontUtil.SetupErrorsViewBag(this, messages);

                foreach (var modelValue in ModelState.Values)
                {
                    modelValue.Errors.Clear();
                }

                abastecimento = service.Read(id);
                return View(new UpdateAbastecimentoViewModel(abastecimento));
            }

            abastecimento = new Abastecimento()
            {
                Id = vm.Id,
                CupomFiscal = vm.CupomFiscal,
                Status = StatusAbastecimento.getInstance(Convert.ToInt32(vm.CodigoStatus))
            };
            service.Update(abastecimento);

            return RedirectToAction("List");
        }




        private void CarregarListaPosto(AbastecimentoViewModel vm)
        {
            IList<Posto> postos = postoService.Read();
            if (vm.Postos == null) vm.Postos = new List<SelectListItem>();
            foreach (Posto posto in postos)
            {
                vm.Postos.Add(
                    new SelectListItem
                    {
                        Value = posto.Id.ToString(),
                        Text = posto.Nome
                    });
            }
        }


        private void CarregarListaMotorista(AbastecimentoViewModel vm)
        {
            IList<Motorista> motoristas = motoristaService.Read();
            if (vm.Motoristas == null) vm.Motoristas = new List<SelectListItem>();
            foreach (Motorista motorista in motoristas)
            {
                vm.Motoristas.Add(

Views/Abastecimento/Create.cshtml
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor accessor
@using Microsoft.AspNetCore.Http
@using System.Text.Json;
@using static UaiFuel.Models.Utils.FrontUtil;


@model AbastecimentoViewModel

@{ 
    decimal total = GetFromSession<decimal>(accessor.HttpContext, "total");
}

<form asp-controller="Abastecimento" asp-action="Create" method="POST">
    <div class="container">
        <div class="wrapper">
            <h2 style="margin-bottom:2rem;">Novo Abastecimento</h2>
            @if (ViewBag.ErrorMessages != null)
            {
                @Html.Raw(ViewBag.ErrorMessages);
            }
            else if (ViewBag.Message != null)
            {
                <div class="@ViewBag.CssClass">
                    @ViewBag.Message
                </div>
            }
            <div class="content">
                <div class="tab_wrap" style="display: block;">
                    <div class="form-group mb-3 row">
                        <label class="col-md-2 col-form-label">
                            Posto
                            <span class="required">*</span>
                        </label>
                        <div class="col-sm-4">

                            @if (ViewBag.FixarPosto != null && ViewBag.FixarPosto == true)
                            {
                                <input readonly="readonly" asp-for="NomePosto" class="form-control input-sm mb-3" />
                                <input type="hidden" asp-for="PostoId" />
                            }
                            else
                            {
                                <select asp-for="PostoId" class="custom-select form-select-lg mb-3">
                                    <option value="0">Selecione</option>
                                    @foreach (var posto in @Model.Postos)
                                    {
                                        <option value="@posto.Value">@posto.Text</option>
                                    }
                                </select>
                            }
                            <input type="hidden" asp-for="NomePosto" />
                        </div>

                        <label class="col-md-2 col-form-label">
                            Status
                            <span class="required">*</span>
                        </label>
                        <div class="col-sm-4">
                            <select asp-for="CodigoStatus" class="custom-select form-select-lg mb-3">
                                <option value="">Selecione</option>
                                @foreach (var status in @Model.Statuses)
                                {
                                    <option value="@status.Value">@status.Text</option>
                                }
                            </select>
                            <span asp-validation-for="CodigoStatus"></span>
                        </div>
                    </div>


                    <div class="form-group mb-3 row">
                        <label class="col-md-2 col-form-label">
                            Motorista
                            <span class="required">*</span>
                        </label>
                        <div class="col-sm-4">
                            <select asp-for="MotoristaId" class="custom-select form-select-lg mb-3">
                                <option value="">Selecione</option>
                                @foreach (var motorista in @Model.Motoristas)
                                {
                                    <option value="@motorista.Value">@motorista.Text</option>
                                }
                            </select>
                            <span asp-validation-for="MotoristaId"></span>
                        </div>

                        <label class="col-md-2 col-form-label" asp-for="CupomFiscal">
                            CupomFiscal
                        </label>
                        <div class="col-sm-4">
                            <input asp-for="CupomFiscal" class="form-control input-sm mb-3" />
                            <span asp-validation-for="CupomFiscal"></span>
                        </div>
                    </div>


                    <div class="form-group mb-3 row">
                        <label class="col-md-2 col-form-label">
                            Veículo
                            <span class="required">*</span>
                        </label>
                        <div class="col-sm-4">
                            <select asp-for="VeiculoPlaca" class="custom-select form-select-lg mb-3">
                                <option value="">Selecione</option>
                                @foreach (var veiculo in @Model.Veiculos)
                                {
                                    <option value="@veiculo.Value">@veiculo.Text</option>
                                }
                            </select>
                            <span asp-validation-for="VeiculoPlaca"></span>
                        </div>

                        <label class="col-md-2 col-form-label" asp-for="ValorTotal">
                            ValorTotal
                        </label>
                        <div class="col-sm-4">
                            <input readonly="readonly" value="R$ @decimal.Round(total, 2, MidpointRounding.AwayFromZero)" class="form-control input-sm mb-3" />
                        </div>
                    </div>


                    <div class="form-group mb-3 row">
                        <label class="col-md-2 col-form-label" asp-for="CombustivelId">
                            Combustível
                        </label>
                        <div class="col-sm-3">
                            <select asp-for="CombustivelId" class="form-control">
                                <option value="">Selecione</option>
                            </select>
                            <span asp-validation-for="CombustivelId"></span>
                            <input type="hidden" asp-for="NomeCombustivel" />
                        </div>

                        <label class="col-md-1 col-form-label" asp-for="Litros">
                            Litros
                        </label>
                        <div class="col-sm-2">
                            <input asp-for="Litros" class="form-control input-sm mb-3" />
                            <span asp-validation-for="Litros"></span>
                        </div>

                        <label class="col-md-1 col-form-label" asp-for="Valor">
                            Valor
                        </label>
                        <div class="form-group col-sm-2">
                            <input asp-for="Valor" class="form-control input-sm mb-3" />
                            <span asp-validation-for="Valor"></span>
                        </div>
                        <div class="col-sm-1" style="padding-left:0px;">
                            <span asp-validation-for="Valor"></span>
                            <button id="adicionarCombustivel" style="margin-top:4px;"
                                    class="btn btn-sm btn-primary">
                                Adicionar
                            </button>
                            <input type="hidden" asp-for="IsBotaoAdicionarCombustivel" />
                        </div>

                    </div>
                </div>
            </div>
        </div>

        <div class="wrapper wrapper_abastecer">
            <button id="abastecer" class="btn btn-primary">Efetuar Abastecimento</button>
        </div>

        <div class="wrapper wrapper_abastecer">
            <h4>Combustíveis do Abastecimento</h4>
            <table class="table table-bordered table-hover table-sm" id="tabela">
                <thead>
                    <tr>
                        <th>Posto</th>
                        <th>Combustível</th>
                        <th>Litros</th>
                        <th>Valor</th>
                    </tr>
                </thead>

                @{
                    List<ItemViewModel> itens = GetFromSession<List<ItemViewModel>>(accessor.HttpContext, "itens");
                    if (itens != null)
                    {
                        @foreach (ItemViewModel item in itens)
                        {
                            <tr>
                                <td>@item.PostoId - @item.NomePosto</td>
                                <td>@item.NomeCombustivel</td>
                                <td>@item.Litros</td>
                                <td>@item.Valor</td>
                            </tr>
                         }
                    }
                 }

            </table>
        </div>
    </div>
</form>

<script>

    // Carregar Combustíveis
    $(document).ready(function () {
        $('#PostoId').change(function () {            
            $.ajax({
                type: "post",
                url: "/Abastecimento/GetCombustiveis",
                data: { postoId: $('#PostoId').val() },
                datatype: "json",
                traditional: true,
                success: function (data) {
                    var combustivel = '<option value="0">Selecione</option>';
                    for (var i = 0; i < data.length; i++) {
                        combustivel = combustivel + '<option value=' + data[i][0] + '>' + data[i][1] + '</option>';
                    }
                    combustivel = combustivel + '</select>';
                    $('#CombustivelId').html(combustivel);
                }
            });
        });
    });


    $(window).on('load', function () {
        let postoId = $('#PostoId').val();
        if (postoId !== "0") {
            $.ajax({
                type: "post",
                url: "/Abastecimento/GetCombustiveis",
                data: { postoId: $('#PostoId').val() },
                datatype: "json",
                traditional: true,
                success: function (data) {
                    var combustivel = '<option value="0">Selecione</option>';
                    for (var i = 0; i < data.length; i++) {
                        combustivel = combustivel + '<option value=' + data[i][0] + '>' + data[i][1] + '</option>';
                    }
                    combustivel = combustivel + '</select>';
                    $('#CombustivelId').html(combustivel);
                }
            });
        }
    });

    $(document).ready(function () {
        $('#adicionarCombustivel').click(function () {
            $('#IsBotaoAdicionarCombustivel').val(true);            
        });
    });

    $(document).ready(function () {
        $('#abastecer').click(function () {
            $('#IsBotaoAdicionarCombustivel').val(false);
        });
    });

    $(document).ready(function () {
        $('#CombustivelId').change(function () {
            $('#NomeCombustivel').val($('#CombustivelId option:selected').text());
        });
    });

    $(document).ready(function () {
        $('#PostoId').change(function () {
            $('#NomePosto').val($('#PostoId option:selected').text());
        });
    });

    $(document).ready(function () {
        $('#Litros').val('');
        $('#Valor').val('');        
    });

   

</script>

Views/Abastecimento/List.cshtml
@model IList<Abastecimento>
@using System.Globalization;

<div class="list_container">
    <h2 style="margin-bottom:2rem;">Abastecimentos Registrados</h2>
    @if (ViewBag.ErrorMessages != null)
    {
        @Html.Raw(ViewBag.ErrorMessages);
    }
    else if (ViewBag.Message != null)
    {
        <div class="@ViewBag.CssClass">
            @ViewBag.Message
        </div>
    }
    <table class="table table-bordered table-hover table-sm" id="sortTable">
        <thead>
            <tr>
                <th>Id</th>
                <th>Data</th>
                <th>ValorTotal</th>
                <th>Posto</th>
                <th>Motorista</th>
                <th>Veículo</th>
                <th>Status</th>
                <th class="col-sm-1">Ação</th>
            </tr>
        </thead>

        @foreach (Abastecimento a in Model)
        {
            <tr>
                <td>@a.Id</td>
                <td>@a.DataCriacao.ToString("dd/MM/yyyy HH:mm")</td>
                <td>R$ @Convert.ToDecimal(decimal.Round(@a.ValorTotal, 2, MidpointRounding.AwayFromZero), new CultureInfo("pt-BR")).ToString()</td>
                <td title="id = @a.Posto.Id">@a.Posto.Nome</td>
                <td title="id = @a.Motorista.Id">@a.Motorista.Nome</td>
                <td>@a.Veiculo.Placa</td>
                <td>@a.Status.Descricao</td>
                <td>
                    <a class="btn btn-sm btn-danger"
                       href="/abastecimento/delete/@a.Id" title="Apagar"><i class="fas fa-trash-alt"></i></a>

                    <a class="btn btn-sm btn-warning"
                       href="/abastecimento/update/@a.Id" title="Editar"><i class="fas fa-edit"></i></a>
                </td>
            </tr>
        }

        <tfoot>
            <tr>
                <td>Id</td>
                <td>Data</td>
                <td>ValorTotal</td>
                <td>Posto</td>
                <td>Motorista</td>
                <td>Veículo</td>
                <td>Status</td>
                <td>Ação</td>
            </tr>
        </tfoot>
    </table>
</div>

<a class="btn btn-primary" href="/abastecimento/create/"><i class="fas fa-plus"></i>   Novo Abastecimento</a>

<script>
    $('#sortTable').DataTable({
    "paging":   true,
    "ordering": true,
    "info":     false,
    "language":{
        "lengthMenu":     "Exibir _MENU_ registros",
        "zeroRecords": "Nenhum registro encontrado",
        "info": "Quantidade de páginas _PAGE_ a _PAGES_",
        "infoEmpty": "Nenhum registro encontrado",
        "infoFiltered": "",
        "search":"Filtro:","paginate": {
                                "first":      "Primeiro",
                                "last":       "Último",
                                "next":       "Próximo",
                                "previous": "Anterior"
                            },
        }
    });

 </script>