Models/Domain/Endereco.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace UaiFuel.Models.Domain
{
    public class Endereco
    {
        public int Id { get; set; }
        public int PostoId { get; set; }
        public string Localidade { get; set; }
        public string CEP { get; set; }
        public Cidade Cidade { get; set; }


        public Endereco() { }


        public override string ToString()
        {
            return $"PostoId:{PostoId} - Id{Id}";
        }
    }
}

Controllers/EnderecoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using UaiFuel.Models.DAO;
using UaiFuel.Models.Domain;
using UaiFuel.Models.ViewModel;

namespace UaiFuel.Controllers
{
    public class EnderecoController : Controller
    {
        
        public ActionResult List()
        {
            List<SelectListItem> nomesEstados = new List<SelectListItem>();
            EstadoCidadeViewModel vm = new EstadoCidadeViewModel();

            IList<Estado> estados = null;
            using (EstadoCidadeDAO dao = new EstadoCidadeDAO())
            {
                estados = dao.GetEstados();
            }
            foreach (var estado in estados)
            {
                nomesEstados.Add(
                    new SelectListItem { Text = estado.Nome, Value = estado.UF });
            }
            vm.NomesEstado = nomesEstados;
            return View(vm);
        }


        [HttpPost]
        public JsonResult GetCidade(string uf)
        {
            List<List<string>> nomesCidade = new List<List<string>>();

            if (!string.IsNullOrEmpty(uf))
            {
                IList<Cidade> cidades = null;
                using (EstadoCidadeDAO dao = new EstadoCidadeDAO())
                {
                    cidades = dao.GetCidades(uf);
                }
                
                foreach (var cidade in cidades)
                {
                    List<string> dict = new List<string>
                    {
                        cidade.Id.ToString(),
                        cidade.Nome
                    };
                    nomesCidade.Add(dict);
                }
            }
            return new JsonResult(nomesCidade);
        }
    }
}

Views/Endereco/List.cshtml
@model EstadoCidadeViewModel

<form asp-controller="Endereco" asp-action="GetCidade" method="POST">
    <h2>Cascading Dropdownlist</h2>
    <table>
        <tr>
            <td>
                <label>Estado</label>
            </td>
            <td>
                @Html.DropDownListFor(e => e.NomesEstado, Model.NomesEstado, "__ Selecione __", new { @id = "estadoIdComponent" })
            </td>
        </tr>
        <tr>
            <td>
                <label>Cidades</label>
            </td>
            <td id="Cidades">
                <select><option>__ Selecione__</option></select>
</td>
        </tr>
    </table>
</form>

<script type="text/javascript">
    $(document).ready(function () {
        $('#estadoIdComponent').change(function () {
            $.ajax({
                type: "post",
                url: "/Endereco/GetCidade",
                data: { uf: $('#estadoIdComponent').val() },
                datatype: "json",
                traditional: true,
                success: function (data) {
                    console.log(data);
                    var cidade = "<select id='cidadeIdComponent'>";
                    cidade = cidade + '<option value="">--Selecione--</option>';
                    for (var i = 0; i < data.length; i++) {
                        cidade = cidade + '<option value=' + data[i][0] + '>' + data[i][1] + '</option>';
                    }
                    cidade = cidade + '</select>';
                    $('#Cidades').html(cidade);
                }
            });
        });
    });
</script>